config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#home'

  get 'about' => 'pages#about'
  get 'thanks' => 'pages#thanks'
  get 'home' => 'pages#home'
  get 'contact' => 'pages#contact'

  get '/signups' => 'signups#index'
  post '/signups' => 'signups#create'
  get '/signups/new' => 'signups#new'
  post '/contact' => 'pages#thanks'

  resources :signups

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/signup.rb
class Signup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home
    end

    def about
    end

    def thanks
    end

    def contact
    end
    
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController

    def new
        @signups = Signups.new
    end

    private
    def signup_params
        params.require(:signups).permit(:firstname, :email)
    end

    def create
        @signup = Signups.new(signup_params)
        redirect.to(@thanks)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stories</title>
  
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <a id="simple-menu" href="#sidr">Menu</a>
  <div id="sidr">
    <ul>
      <li><a href="/home">Home</a></li>
      <!-- <%= link_to "Home", home_path(@home) %> -->
      <li class="active"><a href="/about">About</a></li>
      <li><a href="/contact">Contact</a></li>
    </ul>
  </div>

  <script>
    
  </script>

  <%= yield %>

  <footer class="footer">
    <div class="container">
      <a href="mailto:myemailaddress@gmail.com" class="fas fa-envelope"></a>
      <a href="https://github.com/mmolliss/my-portfolio-app" class="fab fa-github"></a>
      <a href="https://www.linkedin.com/" class="fab fa-linkedin"></a>
      <a href="https://www.facebook.com/" class="fab fa-facebook"></a>
      <a href="https://www.twitter.com/" class="fab fa-twitter"></a>
      <p>© 2020</p>
    </div>
  </footer>
  
  <script src="//cdn.jsdelivr.net/jquery/2.2.0/jquery.min.js"></script>
  <script src="//cdn.jsdelivr.net/jquery.sidr/2.2.1/jquery.sidr.min.js"></script>

  </body>
</html>

app/views/pages/about.html.erb
<main>
    <heading>
        <div class="background-image">
            <div class="container_text">
                <h1>Relive your favourite memories</h1>
            </div>
        </div>
    </heading>

    <div class="about-supporting">
        <div class="container">
            <h2>No more sorting through photos!</h2>
            <p>Stories automatically finds your best photos and creates a new travelogue. This way you can capture and share your special moments in fresh new ways.</p>
            <button type="button">
            <%= link_to "Sign up!", contact_path(@contact) %>
        </div>
    </div>
</main>

app/views/pages/contact.html.erb
<header class="contact_page">
    <div class="contact_image">
        <h1 class="sign_up">Get the latest updates from Stories!</h1>
        <div class="col-md-4"> 
            <%= form_with scope: :signup, local: true do |form| %>
                <div class="form_group">
                    <%= form.label :first_name, 'First name' %>
                    <%= form.text_field :first_name %>
                </div>

                <div class="form_group">
                    <%= form.label :email, 'Email' %>
                    <%= form.text_field :email %>
                </div>
            
                <div class="join_button">
                    <%= form.submit 'Join!' %>
                </div>
            <% end %>
        </div>
    </div>
</header>

app/views/pages/home.html.erb
<main>
  <heading>
    <div class="jumbotron">
      <div class="container">
        <h1>Share your stories!</h1> 
        <button type="button">
            <%= link_to "Learn more!", thanks_path(@thanks) %>   
      </div>
    </div>
  </heading>

    <div class="home-supporting">
        <div class="text">
            <h2>Relive and share your adventures</h2>
            <p>Stories automatically creates a digital journal filled with only your best photos.</p>
        </div>
    </div>

    <div>
        <section class="background-image">
        </section>
    </div>

    <div class="discover">
        <h2>Discover Stories!</h2>
        <button type="button">
        <%= link_to "Learn more!", about_path(@about) %>   
    </div>

    <footer>
    
    </footer>
    </main>

app/views/pages/thanks.html.erb
<main>
    <div class="background-image">
        <div class="container-thanks">
            <h2>Thank you for signing up!</h2>
        </div>
    </div>
</main>

app/views/signups/new.html.erb
<header>
    <form>
        <p>Thanks. We'll be in touch.</p>
    </form>
</header>